#!/usr/bin/env bash
# a script that installs nginx
sudo apt-get update
sudo apt-get install -y ngnix
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" >> /var/www/html/index.html
sudo service ngnix restart
