#!/usr/bin/env bash
# a script that installs nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
string="server_name patricknwosu.tech;\n\trewrite ^/(.*)$ http://patricknwosu.tech/\$1 permanent;"
sudo sed -i "s|server_name _;|$string|" /etc/nginx/sites-available/default
sudo service nginx restart
