#!/usr/bin/env bash
# a script that installs nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo mkdir -p /etc/nginx/error_pages
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/custom_404.html/404.html
string= "listen 80 default_server;\n\terror_page 404 /404.html;\n\tlocation = /404.html {root /usr/share/nginx/html; internal;}"
sed -i "s/listen 80 default_server;/$string/" /etc/nginx/sites-enabled/default
sudo service nginx restart
