#!/usr/bin/env bash
#Describes a loop
count=1
while [ "$count" -lt 21 ];
do
	case $count in
		4)
			echo $count
			echo "bad luck from china"
			;;
		9)
			echo $count
			echo "bad luck from japan"
			;;
		17)
			echo $count
			echo "bad luck from italy"
			;;
		*)
			echo $count
			;;
		esac
	((count++))
done
